version: 3.3.0.{build}

branches:
  only:
  - cpp_master

image:
- Visual Studio 2015
environment:
  global:
    BOOST_PREFIX: C:\Libraries\boost_1_69_0
    BOOST_ROOT: C:\Libraries\boost_1_69_0
  matrix:
    - cpp11: -DMSGPACK_CXX11=OFF
      example:  -DMSGPACK_BUILD_EXAMPLES=OFF
      msvc: '"Visual Studio 10 2010"'
    - cpp11: -DMSGPACK_CXX11=OFF
      example:  -DMSGPACK_BUILD_EXAMPLES=OFF
      msvc: '"Visual Studio 11 2012"'
    - cpp11: -DMSGPACK_CXX11=OFF
      example:  -DMSGPACK_BUILD_EXAMPLES=OFF
      msvc: '"Visual Studio 12 2013"'
    - cpp11: -DMSGPACK_CXX11=ON
      example:  -DMSGPACK_BUILD_EXAMPLES=ON
      msvc: '"Visual Studio 14 2015"'
    - cpp11: -DMSGPACK_CXX11=OFF
      example:  -DMSGPACK_BUILD_EXAMPLES=ON
      msvc: '"Visual Studio 14 2015"'
build_script:
  - ps: |
      appveyor DownloadFile http://zlib.net/zlib-1.2.11.tar.gz -FileName zlib-1.2.11.tar.gz
      7z x zlib-1.2.11.tar.gz 2> $null
      7z x zlib-1.2.11.tar 2> $null
      cd zlib-1.2.11
      md build
      md prefix
      cmake `
          -G $env:msvc `
          -D CMAKE_INSTALL_PREFIX="$env:APPVEYOR_BUILD_FOLDER\zlib-1.2.11\prefix" `
          -B build `
          -S .
      cmake --build build --target install --config Release
      cd ..

      md build
      cmake `
          -G $env:msvc `
          $env:cpp11 `
          $env:example `
          $env:x3_parse `
          -D MSGPACK_BUILD_TESTS=ON `
          -D CMAKE_PREFIX_PATH="$env:BOOST_PREFIX;$env:APPVEYOR_BUILD_FOLDER\zlib-1.2.11\prefix" `
          -D CMAKE_CXX_FLAGS='"/D_VARIADIC_MAX=10 /EHsc"' `
          -B build `
          -S .
      cmake --build build --config Release -v

test_script:
- set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11\build\Release;%APPVEYOR_BUILD_FOLDER%\build\release
- ctest -V

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
