name: coverage

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - cpp_master
    tags:
    - '*'

jobs:
  codecov:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install depends
      run: |
        sudo apt-get update
        sudo apt-get install g++-10-multilib lcov -y

    - name: Cache boost
      id: cache-boost
      uses: actions/cache@v1
      with:
        path: ~/boost-prefix/
        key: ${{ runner.os }}-boost-${{ matrix.arch }}-1-76-0-20210613

    - name: Build boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: ./.github/depends/boost.sh -b ${{ matrix.arch }} -t gcc -p $HOME/boost-prefix/

    - name: Cache zlib
      id: cache-zlib
      uses: actions/cache@v1
      with:
        path: ~/zlib-prefix/
        key: ${{ runner.os }}-zlib-${{ matrix.arch }}-1-2-11-20210613

    - name: Build zlib
      if: steps.cache-zlib.outputs.cache-hit != 'true'
      run: ./.github/depends/zlib.sh -b ${{ matrix.arch }} -p $HOME/zlib-prefix/

    - name: Compile tests
      run: |
        mkdir build
        cmake \
            -DMSGPACK_CXX20=ON \
            -DMSGPACK_32BIT=OFF \
            -DMSGPACK_CHAR_SIGN=signed \
            -DMSGPACK_USE_X3_PARSE=ON \
            -DMSGPACK_BUILD_EXAMPLES=ON \
            -DMSGPACK_BUILD_TESTS=ON \
            -DCMAKE_BUILD_TYPE=Debug \
            -DMSGPACK_GEN_COVERAGE=ON \
            -DCMAKE_PREFIX_PATH="$HOME/zlib-prefix;$HOME/boost-prefix" \
            -B build \
            -S . || exit 1
        cmake --build build --target all || exit 1
        ctest || exit 1

    - name: Upload coverage to Codecov
      working-directory: build
      run: |
        # Create lcov report
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
        lcov --list coverage.info # debug info
        # Uploading report to CodeCov
        bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
